/* AUTO-GENERATED by docs/ui/emit_plugin.py from docs/ui/panel_layout.py — DO NOT EDIT. */
#ifndef LIGASE_PARAMS_H
#define LIGASE_PARAMS_H

typedef enum { LP_INLET, LP_MSG, LP_MSG2, LP_MSGMAP, LP_TOGGLE, LP_SPECIAL, LP_TRIGGER, LP_OUTPUT } lp_kind_t;

typedef struct {
    const char *id; const char *name; const char *group; lp_kind_t kind;
    int inlet; const char *sel; const char *const *map; int nmap; const char *const *labels;
    float lo, hi, def; int is_int, is_bool, is_log, init_send, pow2; const char *unit;
} lp_param_t;

static const char *const lp_labels_recmode[] = { "INPUT", "SPLICE", "OVRDUB" };
static const char *const lp_map_playhead[] = { "playhead 1", "playhead 2", "playhead 3" };
static const char *const lp_labels_playhead[] = { "STATIC", "SCAN", "CLOCK" };
static const char *const lp_map_quantize[] = { NULL, "quantize 1", "quantize 2", "quantize 4", "quantize 8", "quantize 16", "quantize 32", "quantize 64", "quantize 128" };
static const char *const lp_labels_quantize[] = { "OFF", "1/1", "1/2", "1/4", "1/8", "1/16", "1/32", "1/64", "1/128" };
static const char *const lp_map_delay_mode[] = { "delay_mode 0", "delay_mode 1", "delay_mode 2" };
static const char *const lp_labels_delay_mode[] = { "DD-4", "BENCINA", "STUT" };
static const char *const lp_map_delay_quantize[] = { NULL, "delay_quantize 1", "delay_quantize 2", "delay_quantize 4", "delay_quantize 8", "delay_quantize 16", "delay_quantize 32", "delay_quantize 64", "delay_quantize 128" };
static const char *const lp_labels_delay_quantize[] = { "OFF", "1/1", "1/2", "1/4", "1/8", "1/16", "1/32", "1/64", "1/128" };
static const char *const lp_map_smr_mode[] = { "smear_mode 0", "smear_mode 1" };
static const char *const lp_labels_smr_mode[] = { "SNGL", "BANK" };
static const char *const lp_map_env_type[] = { "envelope 0", "envelope 1", "envelope 2", NULL, NULL };
static const char *const lp_labels_env_type[] = { "PARA", "TRAP", "COS", "GAUS", "EXP" };
static const char *const lp_map_pitch_mode[] = { "pitch_mode 0", "pitch_mode 1", "pitch_mode 3", "pitch_mode 4", "pitch_mode 5" };
static const char *const lp_labels_pitch_mode[] = { "OFF", "SEMI", "SCALE", "MIDI", "PATRN" };
static const char *const lp_map_dist_emph[] = { "dist_emphasis_mode 0", "dist_emphasis_mode 1" };
static const char *const lp_labels_dist_emph[] = { "HP", "LP" };
static const char *const lp_map_pan_mode[] = { "pan_mode 0", "pan_mode 1", "pan_mode 2" };
static const char *const lp_labels_pan_mode[] = { "MONO", "STEREO", "SPATIAL" };
static const char *const lp_map_spatial_src[] = { "spatial sphere", "spatial nbody" };
static const char *const lp_labels_spatial_src[] = { "SPHERE", "NBODY" };
static const char *const lp_map_morph_kernel[] = { "morph_interp 0", "morph_interp 1" };
static const char *const lp_labels_morph_kernel[] = { "IDW", "NN" };
static const char *const lp_map_scope_tap[] = { "scope_tap folw", "scope_tap grain" };
static const char *const lp_labels_scope_tap[] = { "FOLW", "GRN" };
static const char *const lp_labels_clock_src[] = { "FREE", "HOST" };

/* DISTORTION preset knob: a preset = a ';'-joined message bundle (panel_layout.DIST_PRESETS) */
static const char *const LIGASE_DIST_PRESETS[8] = {
    "distortion 0.1; dist_waveshaper_mode 0; dist_pregain 1",
    "distortion 0.3; dist_waveshaper_mode 0; dist_pregain 2; dist_curve_blend 0.2",
    "distortion 0.4; dist_waveshaper_mode 1; dist_pregain 2.5; dist_curve_blend 0.4",
    "distortion 0.5; dist_waveshaper_mode 3; dist_pregain 3; dist_curve_blend 0.5",
    "distortion 0.6; dist_waveshaper_mode 2; dist_pregain 4; dist_drive_pos 1.5; dist_drive_neg 1",
    "distortion 0.7; dist_waveshaper_mode 3; dist_pregain 6; dist_curve_blend 0.7",
    "distortion 0.85; dist_waveshaper_mode 4; dist_pregain 6; dist_poly_c1 1; dist_poly_c2 0.5; dist_poly_c3 0.3",
    "distortion 1; dist_waveshaper_mode 4; dist_pregain 8; dist_poly_c1 1; dist_poly_c2 0.8; dist_poly_c3 0.6",
};

static const lp_param_t LIGASE_PARAMS[] = {
    { "grainsize", "GRAIN SIZE", "A. GRANULAR ENGINE", LP_INLET, 3, NULL, NULL, 0, NULL, 0.001f, 2.0f, 0.1f, 0, 0, 0, 1, 0, "s" },
    { "start", "START", "A. GRANULAR ENGINE", LP_INLET, 4, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "speed", "SPEED", "A. GRANULAR ENGINE", LP_INLET, 5, NULL, NULL, 0, NULL, -4.0f, 4.0f, 1.0f, 0, 0, 0, 1, 0, "" },
    { "density", "DENSITY", "A. GRANULAR ENGINE", LP_INLET, 9, NULL, NULL, 0, NULL, 0.001f, 2.0f, 0.1f, 0, 0, 0, 1, 0, "s" },
    { "voices", "VOICES", "A. GRANULAR ENGINE", LP_INLET, 10, NULL, NULL, 0, NULL, 1.0f, 200.0f, 32.0f, 1, 0, 0, 1, 0, "" },
    { "level", "LEVEL", "A. GRANULAR ENGINE", LP_INLET, 21, NULL, NULL, 0, NULL, 0.0f, 2.0f, 1.0f, 0, 0, 0, 1, 0, "" },
    { "organize", "ORGANIZE", "B. TAPE REEL / RECORD", LP_INLET, 6, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "sos", "S.O.S.", "B. TAPE REEL / RECORD", LP_INLET, 8, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "recmode", "REC MODE", "B. TAPE REEL / RECORD", LP_SPECIAL, -1, "recmode", NULL, 0, lp_labels_recmode, 0.0f, 2.0f, 2.0f, 1, 0, 0, 0, 0, "" },
    { "record", "RECORD", "B. TAPE REEL / RECORD", LP_SPECIAL, -1, "record", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 1, 0, 0, 0, "" },
    { "play", "PLAY", "B. TAPE REEL / RECORD", LP_TOGGLE, -1, "play", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 1, 0, 0, 0, "" },
    { "loop", "LOOP / 1-SHOT", "B. TAPE REEL / RECORD", LP_TOGGLE, -1, "loop", NULL, 0, NULL, 0.0f, 1.0f, 1.0f, 0, 1, 0, 1, 0, "" },
    { "playhead", "MODE · playhead 1/2/3", "C. PLAYHEAD + SPLICE SELECT", LP_MSGMAP, -1, NULL, lp_map_playhead, 3, lp_labels_playhead, 0.0f, 2.0f, 1.0f, 1, 0, 0, 1, 0, "" },
    { "scan", "SCAN", "C. PLAYHEAD + SPLICE SELECT", LP_INLET, 7, NULL, NULL, 0, NULL, 0.0f, 8.0f, 1.0f, 0, 0, 0, 1, 0, "" },
    { "quantize", "GRID", "C. PLAYHEAD + SPLICE SELECT", LP_MSGMAP, -1, "quantize", lp_map_quantize, 9, lp_labels_quantize, 0.0f, 8.0f, 0.0f, 1, 0, 0, 0, 1, "" },
    { "quant", "AMOUNT", "C. PLAYHEAD + SPLICE SELECT", LP_MSG, -1, "quant", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "clkadv", "CLK-ADV QUANT", "C. PLAYHEAD + SPLICE SELECT", LP_TOGGLE, -1, "clock_advance_quant", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 1, 0, 0, 0, "" },
    { "delay_mode", "MODE", "D. GRAIN DELAY", LP_MSGMAP, -1, NULL, lp_map_delay_mode, 3, lp_labels_delay_mode, 0.0f, 2.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "dly_time", "TIME · REPS", "D. GRAIN DELAY", LP_INLET, 11, NULL, NULL, 0, NULL, 0.0f, 10.0f, 0.0f, 0, 0, 0, 1, 0, "s" },
    { "dly_feed", "REGEN · DECAY", "D. GRAIN DELAY", LP_INLET, 12, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.3f, 0, 0, 0, 1, 0, "" },
    { "dly_tone", "TONE · SPACE", "D. GRAIN DELAY", LP_INLET, 13, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.5f, 0, 0, 0, 1, 0, "" },
    { "dly_mix", "MIX", "D. GRAIN DELAY", LP_INLET, 14, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "delay_quantize", "GRID", "D. GRAIN DELAY", LP_MSGMAP, -1, "delay_quantize", lp_map_delay_quantize, 9, lp_labels_delay_quantize, 0.0f, 8.0f, 0.0f, 1, 0, 0, 0, 1, "" },
    { "delay_quant", "AMOUNT", "D. GRAIN DELAY", LP_MSG, -1, "delay_quant", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "delay_glide", "GLIDE", "D. GRAIN DELAY", LP_MSG, -1, "delay_glide", NULL, 0, NULL, 0.0f, 5000.0f, 0.0f, 0, 0, 0, 0, 0, "ms" },
    { "cutoff", "CUTOFF", "E. LADDER FILTER + SMEAR", LP_INLET, 16, NULL, NULL, 0, NULL, 20.0f, 20000.0f, 20000.0f, 0, 0, 1, 1, 0, "Hz" },
    { "resonance", "RESONANCE", "E. LADDER FILTER + SMEAR", LP_INLET, 17, NULL, NULL, 0, NULL, 0.0f, 4.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "flt_mix", "MIX", "E. LADDER FILTER + SMEAR", LP_INLET, 18, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "smr_mix", "MIX", "E. LADDER FILTER + SMEAR", LP_INLET, 15, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "smr_freq", "FREQ", "E. LADDER FILTER + SMEAR", LP_MSG, -1, "smear_frequency", NULL, 0, NULL, 20.0f, 20000.0f, 440.0f, 0, 0, 1, 0, 0, "Hz" },
    { "smr_res", "RESON", "E. LADDER FILTER + SMEAR", LP_MSG, -1, "smear_resonance", NULL, 0, NULL, 0.0f, 0.999f, 0.9f, 0, 0, 0, 0, 0, "" },
    { "smr_stages", "STAGES", "E. LADDER FILTER + SMEAR", LP_MSG, -1, "smear_stages", NULL, 0, NULL, 0.0f, 48.0f, 8.0f, 0, 0, 0, 0, 0, "" },
    { "smr_fdbk", "FDBK", "E. LADDER FILTER + SMEAR", LP_MSG, -1, "smear_feedback", NULL, 0, NULL, -0.99f, 0.99f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "smr_mode", "MODE", "E. LADDER FILTER + SMEAR", LP_MSGMAP, -1, NULL, lp_map_smr_mode, 2, lp_labels_smr_mode, 0.0f, 1.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "env_type", "TYPE", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_MSGMAP, -1, NULL, lp_map_env_type, 5, lp_labels_env_type, 0.0f, 4.0f, 2.0f, 1, 0, 0, 1, 0, "" },
    { "skew", "SKEW", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_INLET, 20, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.5f, 0, 0, 0, 1, 0, "" },
    { "saw_cycles", "SAW CYC", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_MSG, -1, "saw_cycles", NULL, 0, NULL, 0.0f, 64.0f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "saw_depth", "SAW DEP", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_MSG, -1, "saw_depth", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "midi_note", "MIDI NOTE", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_INLET, 19, NULL, NULL, 0, NULL, 1.0f, 127.0f, 60.0f, 0, 0, 0, 1, 0, "note" },
    { "pitch_mode", "PITCH MODE", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_MSGMAP, -1, NULL, lp_map_pitch_mode, 5, lp_labels_pitch_mode, 0.0f, 4.0f, 3.0f, 1, 0, 0, 1, 0, "" },
    { "pitch_fine", "FINE", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_MSG, -1, "pitch_fine", NULL, 0, NULL, -50.0f, 50.0f, 0.0f, 0, 0, 0, 0, 0, "ct" },
    { "poly", "POLY ×8", "F. GRAIN ENVELOPE + PITCH/MIDI", LP_TOGGLE, -1, "poly", NULL, 0, NULL, 0.0f, 1.0f, 1.0f, 0, 1, 0, 1, 0, "" },
    { "dist_on", "ON / OFF", "G. DISTORTION + OUTPUT/SPACE", LP_TOGGLE, -1, "distortion_enable", NULL, 0, NULL, 0.0f, 1.0f, 1.0f, 0, 1, 0, 1, 0, "" },
    { "dist_emph", "EMPHASIS", "G. DISTORTION + OUTPUT/SPACE", LP_MSGMAP, -1, NULL, lp_map_dist_emph, 2, lp_labels_dist_emph, 0.0f, 1.0f, 1.0f, 1, 0, 0, 1, 0, "" },
    { "dist_preset", "PRESET", "G. DISTORTION + OUTPUT/SPACE", LP_SPECIAL, -1, "dist_preset", NULL, 0, NULL, 1.0f, 8.0f, 4.0f, 1, 0, 0, 0, 0, "" },
    { "pan", "PAN", "G. DISTORTION + OUTPUT/SPACE", LP_INLET, 22, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.5f, 0, 0, 0, 1, 0, "" },
    { "pan_mode", "PAN MODE", "G. DISTORTION + OUTPUT/SPACE", LP_MSGMAP, -1, NULL, lp_map_pan_mode, 3, lp_labels_pan_mode, 0.0f, 2.0f, 2.0f, 1, 0, 0, 1, 0, "" },
    { "spatial_width", "WIDTH", "G. DISTORTION + OUTPUT/SPACE", LP_MSG, -1, "spatial_width", NULL, 0, NULL, 0.0f, 1.0f, 1.0f, 0, 0, 0, 0, 0, "" },
    { "spatial_src", "SPATIAL SRC", "G. DISTORTION + OUTPUT/SPACE", LP_MSGMAP, -1, NULL, lp_map_spatial_src, 2, lp_labels_spatial_src, 0.0f, 1.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "joy_x", "JOY X", "JOYSTICK / MORPH (X/Y drawn by the bespoke joystick block)", LP_INLET, 23, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.55f, 0, 0, 0, 1, 0, "" },
    { "joy_y", "JOY Y", "JOYSTICK / MORPH (X/Y drawn by the bespoke joystick block)", LP_INLET, 24, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.45f, 0, 0, 0, 1, 0, "" },
    { "morph_kernel", "KERNEL", "JOYSTICK / MORPH (X/Y drawn by the bespoke joystick block)", LP_MSGMAP, -1, NULL, lp_map_morph_kernel, 2, lp_labels_morph_kernel, 0.0f, 1.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "morph_power", "POWER", "JOYSTICK / MORPH (X/Y drawn by the bespoke joystick block)", LP_MSG, -1, "morph_power", NULL, 0, NULL, 0.5f, 8.0f, 2.0f, 0, 0, 0, 0, 0, "" },
    { "scope_tap", "TAP", "SCOPE (display = exact twin of the joystick pad; controls right)", LP_MSGMAP, -1, NULL, lp_map_scope_tap, 2, lp_labels_scope_tap, 0.0f, 1.0f, 0.0f, 1, 0, 0, 0, 0, "" },
    { "master", "MASTER", "MONITOR (condensed: horizontal VU + inline knobs + 2-line legend)", LP_SPECIAL, -1, "master", NULL, 0, NULL, 0.0f, 2.0f, 1.0f, 0, 0, 0, 0, 0, "" },
    { "bank_mix", "BANK MIX", "MONITOR (condensed: horizontal VU + inline knobs + 2-line legend)", LP_MSG, -1, "smear_bank_mix", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, "" },
    { "stut_trig", "STUT (trigger)", "D. GRAIN DELAY", LP_TRIGGER, -1, "stut", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "retrig", "RETRIG (trigger)", "C. PLAYHEAD + SPLICE SELECT", LP_TRIGGER, -1, "trigger", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "clock_src", "CLOCK SOURCE", "PLUGIN", LP_SPECIAL, -1, "clock_src", NULL, 0, lp_labels_clock_src, 0.0f, 1.0f, 1.0f, 0, 0, 0, 1, 0, "" },
    { "midi_ch_grain", "MIDI CH (GRAIN)", "PLUGIN", LP_MSG2, -1, "midi_channel", NULL, 0, NULL, 1.0f, 16.0f, 1.0f, 1, 0, 0, 1, 0, "" },
    { "midi_ch_smear", "MIDI CH (SMEAR)", "PLUGIN", LP_MSG2, -1, "midi_channel", NULL, 0, NULL, 1.0f, 16.0f, 2.0f, 1, 0, 0, 1, 0, "" },
    { "midi_vel_amp", "VELOCITY -> LEVEL", "PLUGIN", LP_SPECIAL, -1, "midi_vel_amp", NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "midi_bend_cents", "PITCH BEND RANGE", "PLUGIN", LP_SPECIAL, -1, "midi_bend_cents", NULL, 0, NULL, 0.0f, 50.0f, 50.0f, 1, 0, 0, 1, 0, "" },
    { "vu_l", "OUT L PEAK", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 4.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "vu_r", "OUT R PEAK", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 4.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_splice", "SPLICE", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 2000.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "o_splices", "SPLICE COUNT", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 2000.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "o_playing", "PLAYING", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_recording", "RECORDING", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 1.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_bpm", "BPM", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 999.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_reel_sec", "REEL SECONDS", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 600.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_grains", "ACTIVE GRAINS", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 2000.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "o_voices", "VOICES", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, 0.0f, 8.0f, 0.0f, 1, 0, 0, 1, 0, "" },
    { "o_modout1", "MODOUT 1", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, -1000000.0f, 1000000.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_modout2", "MODOUT 2", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, -1000000.0f, 1000000.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_modout3", "MODOUT 3", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, -1000000.0f, 1000000.0f, 0.0f, 0, 0, 0, 1, 0, "" },
    { "o_modout4", "MODOUT 4", "OUTPUTS", LP_OUTPUT, -1, NULL, NULL, 0, NULL, -1000000.0f, 1000000.0f, 0.0f, 0, 0, 0, 1, 0, "" },
};
#define LIGASE_PARAM_COUNT 77
#define LIGASE_PARAM_SPACE 64   /* engine snapshot slot reserved for the plugin's live-voice capture */
#define LP_GRAINSIZE 0
#define LP_START 1
#define LP_SPEED 2
#define LP_DENSITY 3
#define LP_VOICES 4
#define LP_LEVEL 5
#define LP_ORGANIZE 6
#define LP_SOS 7
#define LP_RECMODE 8
#define LP_RECORD 9
#define LP_PLAY 10
#define LP_LOOP 11
#define LP_PLAYHEAD 12
#define LP_SCAN 13
#define LP_QUANTIZE 14
#define LP_QUANT 15
#define LP_CLKADV 16
#define LP_DELAY_MODE 17
#define LP_DLY_TIME 18
#define LP_DLY_FEED 19
#define LP_DLY_TONE 20
#define LP_DLY_MIX 21
#define LP_DELAY_QUANTIZE 22
#define LP_DELAY_QUANT 23
#define LP_DELAY_GLIDE 24
#define LP_CUTOFF 25
#define LP_RESONANCE 26
#define LP_FLT_MIX 27
#define LP_SMR_MIX 28
#define LP_SMR_FREQ 29
#define LP_SMR_RES 30
#define LP_SMR_STAGES 31
#define LP_SMR_FDBK 32
#define LP_SMR_MODE 33
#define LP_ENV_TYPE 34
#define LP_SKEW 35
#define LP_SAW_CYCLES 36
#define LP_SAW_DEPTH 37
#define LP_MIDI_NOTE 38
#define LP_PITCH_MODE 39
#define LP_PITCH_FINE 40
#define LP_POLY 41
#define LP_DIST_ON 42
#define LP_DIST_EMPH 43
#define LP_DIST_PRESET 44
#define LP_PAN 45
#define LP_PAN_MODE 46
#define LP_SPATIAL_WIDTH 47
#define LP_SPATIAL_SRC 48
#define LP_JOY_X 49
#define LP_JOY_Y 50
#define LP_MORPH_KERNEL 51
#define LP_MORPH_POWER 52
#define LP_SCOPE_TAP 53
#define LP_MASTER 54
#define LP_BANK_MIX 55
#define LP_STUT_TRIG 56
#define LP_RETRIG 57
#define LP_CLOCK_SRC 58
#define LP_MIDI_CH_GRAIN 59
#define LP_MIDI_CH_SMEAR 60
#define LP_MIDI_VEL_AMP 61
#define LP_MIDI_BEND_CENTS 62
#define LP_VU_L 63
#define LP_VU_R 64
#define LP_O_SPLICE 65
#define LP_O_SPLICES 66
#define LP_O_PLAYING 67
#define LP_O_RECORDING 68
#define LP_O_BPM 69
#define LP_O_REEL_SEC 70
#define LP_O_GRAINS 71
#define LP_O_VOICES 72
#define LP_O_MODOUT1 73
#define LP_O_MODOUT2 74
#define LP_O_MODOUT3 75
#define LP_O_MODOUT4 76

#endif
